.github/workflows/update-best-of-list.yml
projects.yaml

- [Integrate Gitee into best-of-generator](https://github.com/YDX-2147483647/best-of-generator/tree/gitee).
- Update [best-of-update-action](https://github.com/YDX-2147483647/best-of-update-action/tree/best-of-bits) to use the generator.
- Add projects from Gitee.
- #20
- #21
- https://github.com/YDX-2147483647/best-of-bits/actions/runs/4832728187 
- #22
- #24
- https://github.com/YDX-2147483647/best-of-bits/actions/runs/4843263559
- #25

Add Gitee projects

---

projects.yaml

Resolves #5
描述被认为太长时，会被截断，而截断算法不适用于中文。
效果如下。
https://github.com/YDX-2147483647/best-of-bits/actions/runs/4970951305
https://github.com/YDX-2147483647/best-of-bits/blob/124f1e878b47340a2a988d5ab0daff60f90356ea/README.md

[config] Higher max_description_length

---

.github/ISSUE_TEMPLATE/01_suggest-project.yml
CONTRIBUTING.md
scripts/add_project.py

- 议题模板
- 贡献者指南中的简易文档
- 自动化脚本
Resolves #71

doc, ci: 提及支持非 GitHub 项目

---

projects.yaml

[projects] Add GitHub ID for BIT-Moodle-Theme-Enhance

---

projects.yaml

Resolves #80, #81, #82, #83, #84

[projects] Add projects

---

.github/workflows/update-best-of-list.yml

Resolves #90
https://github.com/YDX-2147483647/best-of-bits/actions/runs/5689367664/job/15420746575

ci: Use forked best-of-generator directly

---

CONTRIBUTING.md

doc: `/draft-pr`机器人

---

.github/workflows/update-best-of-list.yml
config/header.md

[config] 降低更新频率至一月

---

CONTRIBUTING.md
config/footer.md

https://github.com/orgs/community/discussions/16925
2023-07-21: A new syntax, `[!NOTE]`, has been added, which will gradually replace the old one.

doc: Update alert syntax in markdown

---

projects.yaml

[projects] 新增项目：bit-genshin

---

CONTRIBUTING.md
config/footer.md

现在已经不用 best-of-update-action，有些地方没更新。
Relates-to: #89
Relates-to: #91
Relates-to: https://github.com/YDX-2147483647/best-of-update-action/commit/9f393c2b6c838d943afc12cd9088c04fdd2b06b7

doc: Remove forked best-of-update-action

---

projects.yaml

[projects] 新增项目：BITlife

---

projects.yaml

Resolves #176
This partially reverts 44432cfa8c46d1b05b756d6b5fb5d1798b661884 and fd04b5a7fff8c36ca3f0a16d0df9f07c37a22b5a.

[projects] 更正 BITCS-final-exam-learning-materials

---

projects.yaml

[category] Quote `*.edu.cn`

---

projects.yaml

[projects] 更新 bitsrunlogin 的 github_id

---

projects.yaml

[projects] 更正 BIT_Second_Round_Exam

---

projects.yaml

https://github.com/YDX-2147483647/BIT-enhanced/pull/18 将这个项目合并进了 BIT-enhanced，并上传到了 Greasy Fork。
Resolves #196
Relates-to: #191
Relates-to: #86

[projects] “导出物理实验课表”合并进了 BIT-enhanced

---

projects.yaml

[projects] 新增项目：北京理工大学学术答辩PPT模板（BITPPT）

---

projects.yaml

[projects] 新增项目/更改项目：BITPPT v4.0

---

projects.yaml

[projects] 新增项目：BITNP 新生电脑选购指南

---

projects.yaml

新增项目：北京理工大学物理实验报告
